routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::post('admin/login', 'UserController@checkadmin');
Route::post('user/login', 'UserController@checkusers');
Route::get('session', 'UserController@session');
Route::resource('channels', 'ChannelsController');

Route::post('channel/create', 'ChannelsController@store');
Route::patch('channel/update', 'ChannelsController@update')->name('channel.update');
Route::delete('channel/delete', 'ChannelsController@destroy')->name('channel.destroy');

Route::get('messages/{sid}', 'MessagesController@index');
Route::get('channelslist', 'ChannelslistController@index');
Route::post('channelslist/create', 'ChannelslistController@store')->name('channelslist.create');
Route::post('message/send', 'MessagesController@store');

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

app/Http/Controllers/ChannelsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Twilio\Rest\Client;

class ChannelsController extends Controller
{
    
    protected $sid;
    protected $token;

    public function __construct()
    {
        $this->sid = 'ACd00a327fb16cf8774eff2bed6e878174';
        $this->token = '061207aab9897f7f3b6b32f7ec6ee834';
    }
    /**
     * Display a listing of the channels.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $twilio = new Client($this->sid, $this->token);
        $services = $twilio->chat->v2->services->read();
        $channels = $twilio->chat->v2->services($services[0]->sid)->channels->read();
        return view('channels.index', compact('channels'));
    }

    /**
     * Show the form for creating a new channel.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('channels.create');
    }

    /**
     * create a new channel in a service.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
        'nombre'   => 'required'
        ]);
        $twilio = new Client($this->sid, $this->token);
        $services = $twilio->chat->v2->services->read();
        $channel = $twilio->chat->v2->services($services[0]->sid)->channels->create(array("friendlyName" => $request->get('nombre')));
        return redirect('channels');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified channel.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($sid)
    {
        $twilio = new Client($this->sid, $this->token);
        $services = $twilio->chat->v2->services->read();
        $channels = $twilio->chat->v2->services($services[0]->sid)->channels->read();
        foreach ($channels as $record) {
            if ($record->sid == $sid) {
                $channel = $record;
            }
        }
        return view('channels.update', compact('channel'));
    }

    /**
     * Update the specified channel in a service.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $twilio = new Client($this->sid, $this->token);
        $services = $twilio->chat->v2->services->read();
        $channel = $twilio->chat->v2->services($services[0]->sid)->channels($request->get('sid'))->update(array("friendlyName" => $request->get('nombre')));
        return redirect('channels');
    }

    /**
     * Remove the specified channel from service.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($sid)
    {
        $twilio = new Client($this->sid, $this->token);
        $services = $twilio->chat->v2->services->read();
        $twilio->chat->v2->services($services[0]->sid)->channels($sid)->delete();
        return redirect('channels');
    }
}

resources/views/channels/create.blade.php
@extends('layouts.app')
<link href="{{ asset('css/background.css') }}" rel="stylesheet">
@section('tittle', 'Add new channel')
@section('content')
<br><br><br><br><br><br><br><br>
<div class="container" style="background-color: white; border-radius: 10px; border: solid 1px;">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <h2 class="text-center">Add Channel</h2><br>
        <form class="login-form text-center" method="POST" action="{{url('/channel/create')}}">
            <div class="row">
                <div class="col">
                  @csrf
                  <div class="first">
                    <div class="form-group">
                      <label for="nombre" class="text-uppercase">Nombre</label>
                      <input type="text" name="nombre" id="nombre" class="form-control{{ $errors->has('nombre') ? ' is-invalid' : '' }}" placeholder="Name" value="{{ old('nombre') }}" required>
                       @if ($errors->has('nombre'))
                        <span class="invalid-feedback" role="alert">
                          <strong>{{ $errors->first('nombre') }}</strong>
                        </span>
                      @endif
                      <br><br>
                      <button class="btn btn-primary">AGREGAR</button> 
                  </div>
                  </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/channels/index.blade.php
@extends('layouts.app')
<link href="{{ asset('css/background.css') }}" rel="stylesheet">
@section('tittle', 'Channels')
@section('content')
<br>
<div class="container">
	<div class="col-sm-12">
		<h2>CANALES</h2><br>
		<a href="{{route('channels.create')}}" class="btn btn-success" style="right: 40px; position: absolute;">
			AGREGAR <i class="fas fa-plus-square"></i>
	    </a>
	    <br>
	    <br>
		<table class="table table-hover table-striped table-bordered" style="width: 98%">
			<thead>
				<tr style="background-color: gray">
					<th style="text-align: center;">SID</th>
					<th style="text-align: center;">NOMBRE</th>
					<th style="text-align: center;">FECHA DE CREACIÓN</th>
					<th style="text-align: center;">FECHA DE ACTUALIZACIÓN</th>
					<th style="text-align: center;" colspan="2">ACCIÓN</th>
				</tr>
			</thead>
			<tbody>
				@foreach($channels as $channel)
				<tr style="background-color: #BFBEBE">
					<td>{{$channel->sid}}</td>
					<td>{{$channel->friendlyName}}</td>
					<td>{{date_format($channel->dateCreated, 'd/m/Y')}}</td>
					<td>{{date_format($channel->dateUpdated, 'd/m/Y')}}</td>
					<td>
						<a href="{{route('channels.edit', $channel->sid) }}" class="btn btn-primary">
							<i class="fas fa-edit"></i>
	                    </a>
	                </td>
					<td>
						<form  method="POST" action="{{ route('channels.destroy', $channel->sid) }}">
							{{ csrf_field() }}
							<input type="hidden" name="_method" value="DELETE">
							<button class="btn btn-danger">
	                                <i class="fas fa-trash-alt"></i>
	                        </button>
						</form>
	                </td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
@endsection
</div>

resources/views/channels/update.blade.php
@extends('layouts.app')
<link href="{{ asset('css/background.css') }}" rel="stylesheet">
@section('tittle', 'Update channel')
@section('content')
<div class="container" style="border-radius: 10px;">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="text-center">Update Channel</h2><br>
        <form class="login-form" method="post" action="{{route('channel.update')}}" enctype="multipart/form-data">
            @csrf
            <input name="_method" type="hidden" value="PATCH">
            <div class="row" style="background-color: white">
                <div class="col-md-9">
                  <div class="form-group">
                    <label>SID</label>
                    <input type="hidden" name="sid" value="{{ $channel->sid }}">
                    <input type="text" name="sidChannel" class="form-control" required placeholder="Código" value="{{ $channel->sid }}" disabled="disabled">
                  </div>
                  <div class="form-group">
                    <label>NOMBRE</label>
                    <input type="text" name="nombre" class="form-control" required value="{{ $channel->friendlyName }}">
                  </div>
                  <div class="form-group">
                    <label>FECHA DE CREACIÓN</label>
                    <input type="text" name="datecrea" class="form-control" required value="{{ date_format($channel->dateCreated, 'd/m/Y') }}" disabled="disabled">
                  </div>
                  <div class="form-group">
                    <label>FECHA DE ACTUALIZACIÓN</label>
                    <input type="text" name="dateact" class="form-control" required value="{{ date_format($channel->dateUpdated, 'd/m/Y') }}" disabled="disabled">
                  </div>
                </div>
            </div>
            <br>
            <button class="btn btn-primary" type="submit">
              MODIFICAR
            </button>

                
        </form>
    </div>
</div>
@endsection